version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user_service:
    build: ./user_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./user_service:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookdb
    ports:
      - "8001:8001"

  book_service:
    build: ./book_service
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./book_service:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookdb
    ports:
      - "8002:8002"

  reading_service:
    build: ./reading_service
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    volumes:
      - ./reading_service:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookdb
    ports:
      - "8003:8003"

  api_gateway:
    build: ./api_gateway
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api_gateway:/app
    depends_on:
      - user_service
      - book_service
      - reading_service
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - api_gateway

volumes:
  pgdata:
